#*******************************************************************************
#                           Config Data source
#******************************************************************************/

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 100
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/salondb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    hikari:
      data-source-properties:
        useUnicode: true
  #*******************************************************************************
  #                           Google Service
  #******************************************************************************/
service:
  google:
    drive-api:
      credentials: classpath:google_credentials/staging/credentials.json